-- =============================================================
-- 00029: CLIENTES igual a Polaris (form_tb_customers /
-- grid_tb_customers + historial, verificado en QA 2026-06-12).
-- Se extiende la tabla clients existente (la usan órdenes, pagos
-- y reservaciones) con los campos del formulario Polaris:
--   tipo de persona (1 Jurídica / 2 Natural, códigos Polaris),
--   tipo de documento (CC / NIT), responsable fiscal y régimen
--   IVA (códigos DIAN), apellidos, género, fecha de nacimiento,
--   código de verificación (NIT), teléfono 2, notas y geografía
--   país → departamento → ciudad (Colombia completa, DIVIPOLA).
-- clients_audit reemplaza al "Historial" de Polaris guardando el
-- nombre del cliente (Polaris muestra "No definido" tras borrar)
-- y el detalle ya legible (Polaris muestra códigos crudos).
-- =============================================================

CREATE TABLE geo_departments (
  id   SERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE geo_cities (
  id            SERIAL PRIMARY KEY,
  department_id INT NOT NULL REFERENCES geo_departments(id),
  name          TEXT NOT NULL,
  UNIQUE (department_id, name)
);

ALTER TABLE clients
  ADD COLUMN person_type SMALLINT NOT NULL DEFAULT 2
    CONSTRAINT chk_clients_person_type CHECK (person_type IN (1, 2)),
  ADD COLUMN document_type TEXT NOT NULL DEFAULT 'CC'
    CONSTRAINT chk_clients_document_type CHECK (document_type IN ('CC', 'NIT')),
  ADD COLUMN fiscal_responsibility TEXT NOT NULL DEFAULT 'R-99-PN'
    CONSTRAINT chk_clients_fiscal CHECK (fiscal_responsibility IN
      ('R-99-PN', 'O-47', 'O-23', 'O-15', 'O-13')),
  ADD COLUMN tax_regime TEXT NOT NULL DEFAULT '49'
    CONSTRAINT chk_clients_tax_regime CHECK (tax_regime IN ('48', '49')),
  ADD COLUMN last_name TEXT,
  ADD COLUMN gender TEXT NOT NULL DEFAULT 'Masculino'
    CONSTRAINT chk_clients_gender CHECK (gender IN ('Masculino', 'Femenino')),
  ADD COLUMN birthday DATE,
  ADD COLUMN verification_code TEXT,
  ADD COLUMN phone2 TEXT,
  ADD COLUMN notes TEXT,
  ADD COLUMN country TEXT NOT NULL DEFAULT 'COLOMBIA',
  ADD COLUMN department_id INT REFERENCES geo_departments(id),
  ADD COLUMN city_id INT REFERENCES geo_cities(id);

-- Historial de clientes (grid "Historial" de Polaris):
-- Creación = registro completo, Actualización = solo campos
-- cambiados, Eliminación = sin detalle. client_id sin FK para
-- conservar las entradas tras el borrado físico del cliente.
CREATE TABLE clients_audit (
  id          SERIAL PRIMARY KEY,
  tenant_id   UUID NOT NULL REFERENCES tenants(id),
  client_id   INT,
  client_name TEXT NOT NULL,
  user_name   TEXT NOT NULL,
  action      TEXT NOT NULL
    CONSTRAINT chk_clients_audit_action CHECK (action IN ('create', 'update', 'delete')),
  detail      JSONB,
  created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_clients_audit_tenant ON clients_audit(tenant_id, created_at DESC);

-- ───────── Seed geografía: 33 departamentos / 1.103 municipios ─────────
INSERT INTO geo_departments (name) VALUES
  ('AMAZONAS'),
  ('ANTIOQUIA'),
  ('ARAUCA'),
  ('ATLÁNTICO'),
  ('BOGOTÁ D.C.'),
  ('BOLÍVAR'),
  ('BOYACÁ'),
  ('CALDAS'),
  ('CAQUETÁ'),
  ('CASANARE'),
  ('CAUCA'),
  ('CESAR'),
  ('CHOCÓ'),
  ('CÓRDOBA'),
  ('CUNDINAMARCA'),
  ('GUAINÍA'),
  ('GUAVIARE'),
  ('HUILA'),
  ('LA GUAJIRA'),
  ('MAGDALENA'),
  ('META'),
  ('NARIÑO'),
  ('NORTE DE SANTANDER'),
  ('PUTUMAYO'),
  ('QUINDÍO'),
  ('RISARALDA'),
  ('SAN ANDRÉS Y PROVIDENCIA'),
  ('SANTANDER'),
  ('SUCRE'),
  ('TOLIMA'),
  ('VALLE DEL CAUCA'),
  ('VAUPÉS'),
  ('VICHADA');

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Leticia',
  'Puerto Nariño'
]) AS c WHERE name = 'AMAZONAS';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Abejorral',
  'Abriaquí',
  'Alejandría',
  'Amagá',
  'Amalfi',
  'Andes',
  'Angelópolis',
  'Angostura',
  'Anorí',
  'Anzá',
  'Apartadó',
  'Arboletes',
  'Argelia',
  'Armenia',
  'Barbosa',
  'Bello',
  'Belmira',
  'Betania',
  'Betulia',
  'Briceño',
  'Buriticá',
  'Cáceres',
  'Caicedo',
  'Caldas',
  'Campamento',
  'Cañasgordas',
  'Caracolí',
  'Caramanta',
  'Carepa',
  'Carolina del Príncipe',
  'Caucasia',
  'Chigorodó',
  'Cisneros',
  'Ciudad Bolívar',
  'Cocorná',
  'Concepción',
  'Concordia',
  'Copacabana',
  'Dabeiba',
  'Donmatías',
  'Ebéjico',
  'El Bagre',
  'El Carmen de Viboral',
  'El Peñol',
  'El Retiro',
  'El Santuario',
  'Entrerríos',
  'Envigado',
  'Fredonia',
  'Frontino',
  'Giraldo',
  'Girardota',
  'Gómez Plata',
  'Granada',
  'Guadalupe',
  'Guarne',
  'Guatapé',
  'Heliconia',
  'Hispania',
  'Itagüí',
  'Ituango',
  'Jardín',
  'Jericó',
  'La Ceja',
  'La Estrella',
  'La Pintada',
  'La Unión',
  'Liborina',
  'Maceo',
  'Marinilla',
  'Medellín',
  'Montebello',
  'Murindó',
  'Mutatá',
  'Nariño',
  'Nechí',
  'Necoclí',
  'Olaya',
  'Peque',
  'Pueblorrico',
  'Puerto Berrío',
  'Puerto Nare',
  'Puerto Triunfo',
  'Remedios',
  'Rionegro',
  'Sabanalarga',
  'Sabaneta',
  'Salgar',
  'San Andrés de Cuerquia',
  'San Carlos',
  'San Francisco',
  'San Jerónimo',
  'San José de la Montaña',
  'San Juan de Urabá',
  'San Luis',
  'San Pedro de Urabá',
  'San Pedro de los Milagros',
  'San Rafael',
  'San Roque',
  'San Vicente',
  'Santa Bárbara',
  'Santa Fe de Antioquia',
  'Santa Rosa de Osos',
  'Santo Domingo',
  'Segovia',
  'Sonsón',
  'Sopetrán',
  'Támesis',
  'Tarazá',
  'Tarso',
  'Titiribí',
  'Toledo',
  'Turbo',
  'Uramita',
  'Urrao',
  'Valdivia',
  'Valparaíso',
  'Vegachí',
  'Venecia',
  'Vigía del Fuerte',
  'Yalí',
  'Yarumal',
  'Yolombó',
  'Yondó',
  'Zaragoza'
]) AS c WHERE name = 'ANTIOQUIA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Arauca',
  'Arauquita',
  'Cravo Norte',
  'Fortul',
  'Puerto Rondón',
  'Saravena',
  'Tame'
]) AS c WHERE name = 'ARAUCA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Baranoa',
  'Barranquilla',
  'Campo de la Cruz',
  'Candelaria',
  'Galapa',
  'Juan de Acosta',
  'Luruaco',
  'Malambo',
  'Manatí',
  'Palmar de Varela',
  'Piojó',
  'Polonuevo',
  'Ponedera',
  'Puerto Colombia',
  'Repelón',
  'Sabanagrande',
  'Sabanalarga',
  'Santa Lucía',
  'Santo Tomás',
  'Soledad',
  'Suán',
  'Tubará',
  'Usiacurí'
]) AS c WHERE name = 'ATLÁNTICO';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Bogotá D.C.'
]) AS c WHERE name = 'BOGOTÁ D.C.';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Achí',
  'Altos del Rosario',
  'Arenal',
  'Arjona',
  'Arroyohondo',
  'Barranco de Loba',
  'Brazuelo de Papayal',
  'Calamar',
  'Cantagallo',
  'Cartagena de Indias',
  'Cicuco',
  'Clemencia',
  'Córdoba',
  'El Carmen de Bolívar',
  'El Guamo',
  'El Peñón',
  'Hatillo de Loba',
  'Magangué',
  'Mahates',
  'Margarita',
  'María la Baja',
  'Mompós',
  'Montecristo',
  'Morales',
  'Norosí',
  'Pinillos',
  'Regidor',
  'Río Viejo',
  'San Cristóbal',
  'San Estanislao',
  'San Fernando',
  'San Jacinto del Cauca',
  'San Jacinto',
  'San Juan Nepomuceno',
  'San Martín de Loba',
  'San Pablo',
  'Santa Catalina',
  'Santa Rosa',
  'Santa Rosa del Sur',
  'Simití',
  'Soplaviento',
  'Talaigua Nuevo',
  'Tiquisio',
  'Turbaco',
  'Turbaná',
  'Villanueva',
  'Zambrano'
]) AS c WHERE name = 'BOLÍVAR';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Almeida',
  'Aquitania',
  'Arcabuco',
  'Belén',
  'Berbeo',
  'Betéitiva',
  'Boavita',
  'Boyacá',
  'Briceño',
  'Buenavista',
  'Busbanzá',
  'Caldas',
  'Campohermoso',
  'Cerinza',
  'Chinavita',
  'Chiquinquirá',
  'Chíquiza',
  'Chiscas',
  'Chita',
  'Chitaraque',
  'Chivatá',
  'Chivor',
  'Ciénega',
  'Cómbita',
  'Coper',
  'Corrales',
  'Covarachía',
  'Cubará',
  'Cucaita',
  'Cuítiva',
  'Duitama',
  'El Cocuy',
  'El Espino',
  'Firavitoba',
  'Floresta',
  'Gachantivá',
  'Gámeza',
  'Garagoa',
  'Guacamayas',
  'Guateque',
  'Guayatá',
  'Güicán',
  'Iza',
  'Jenesano',
  'Jericó',
  'La Capilla',
  'La Uvita',
  'La Victoria',
  'Labranzagrande',
  'Macanal',
  'Maripí',
  'Miraflores',
  'Mongua',
  'Monguí',
  'Moniquirá',
  'Motavita',
  'Muzo',
  'Nobsa',
  'Nuevo Colón',
  'Oicatá',
  'Otanche',
  'Pachavita',
  'Páez',
  'Paipa',
  'Pajarito',
  'Panqueba',
  'Pauna',
  'Paya',
  'Paz del Río',
  'Pesca',
  'Pisba',
  'Puerto Boyacá',
  'Quípama',
  'Ramiriquí',
  'Ráquira',
  'Rondón',
  'Saboyá',
  'Sáchica',
  'Samacá',
  'San Eduardo',
  'San José de Pare',
  'San Luis de Gaceno',
  'San Mateo',
  'San Miguel de Sema',
  'San Pablo de Borbur',
  'Santa María',
  'Santa Rosa de Viterbo',
  'Santa Sofía',
  'Santana',
  'Sativanorte',
  'Sativasur',
  'Siachoque',
  'Soatá',
  'Socha',
  'Socotá',
  'Sogamoso',
  'Somondoco',
  'Sora',
  'Soracá',
  'Sotaquirá',
  'Susacón',
  'Sutamarchán',
  'Sutatenza',
  'Tasco',
  'Tenza',
  'Tibaná',
  'Tibasosa',
  'Tinjacá',
  'Tipacoque',
  'Toca',
  'Togüí',
  'Tópaga',
  'Tota',
  'Tunja',
  'Tununguá',
  'Turmequé',
  'Tuta',
  'Tutazá',
  'Úmbita',
  'Ventaquemada',
  'Villa de Leyva',
  'Viracachá',
  'Zetaquira'
]) AS c WHERE name = 'BOYACÁ';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Aguadas',
  'Anserma',
  'Aranzazu',
  'Belalcázar',
  'Chinchiná',
  'Filadelfia',
  'La Dorada',
  'La Merced',
  'Manizales',
  'Manzanares',
  'Marmato',
  'Marquetalia',
  'Marulanda',
  'Neira',
  'Norcasia',
  'Pácora',
  'Palestina',
  'Pensilvania',
  'Riosucio',
  'Risaralda',
  'Salamina',
  'Samaná',
  'San José',
  'Supía',
  'Victoria',
  'Villamaría',
  'Viterbo'
]) AS c WHERE name = 'CALDAS';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Albania',
  'Belén de los Andaquíes',
  'Cartagena del Chairá',
  'Curillo',
  'El Doncello',
  'El Paujil',
  'Florencia',
  'La Montañita',
  'Milán',
  'Morelia',
  'Puerto Rico',
  'San José del Fragua',
  'San Vicente del Caguán',
  'Solano',
  'Solita',
  'Valparaíso'
]) AS c WHERE name = 'CAQUETÁ';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Aguazul',
  'Chámeza',
  'Hato Corozal',
  'La Salina',
  'Maní',
  'Monterrey',
  'Nunchía',
  'Orocué',
  'Paz de Ariporo',
  'Pore',
  'Recetor',
  'Sabanalarga',
  'Sácama',
  'San Luis de Palenque',
  'Támara',
  'Tauramena',
  'Trinidad',
  'Villanueva',
  'Yopal'
]) AS c WHERE name = 'CASANARE';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Almaguer',
  'Argelia',
  'Balboa',
  'Bolívar',
  'Buenos Aires',
  'Cajibío',
  'Caldono',
  'Caloto',
  'Corinto',
  'El Tambo',
  'Florencia',
  'Guachené',
  'Guapí',
  'Inzá',
  'Jambaló',
  'La Sierra',
  'La Vega',
  'López de Micay',
  'Mercaderes',
  'Miranda',
  'Morales',
  'Padilla',
  'Páez',
  'Patía',
  'Piamonte',
  'Piendamó',
  'Popayán',
  'Puerto Tejada',
  'Puracé',
  'Rosas',
  'San Sebastián',
  'Santa Rosa',
  'Santander de Quilichao',
  'Silvia',
  'Sotará',
  'Suárez',
  'Sucre',
  'Timbío',
  'Timbiquí',
  'Toribío',
  'Totoró',
  'Villa Rica'
]) AS c WHERE name = 'CAUCA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Aguachica',
  'Agustín Codazzi',
  'Astrea',
  'Becerril',
  'Bosconia',
  'Chimichagua',
  'Chiriguaná',
  'Curumaní',
  'El Copey',
  'El Paso',
  'Gamarra',
  'González',
  'La Gloria (Cesar)',
  'La Jagua de Ibirico',
  'La Paz',
  'Manaure Balcón del Cesar',
  'Pailitas',
  'Pelaya',
  'Pueblo Bello',
  'Río de Oro',
  'San Alberto',
  'San Diego',
  'San Martín',
  'Tamalameque',
  'Valledupar'
]) AS c WHERE name = 'CESAR';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Acandí',
  'Alto Baudó',
  'Bagadó',
  'Bahía Solano',
  'Bajo Baudó',
  'Bojayá',
  'Cantón de San Pablo',
  'Cértegui',
  'Condoto',
  'El Atrato',
  'El Carmen de Atrato',
  'El Carmen del Darién',
  'Istmina',
  'Juradó',
  'Litoral de San Juan',
  'Lloró',
  'Medio Atrato',
  'Medio Baudó',
  'Medio San Juan',
  'Nóvita',
  'Nuquí',
  'Quibdó',
  'Río Iró',
  'Río Quito',
  'Riosucio',
  'San José del Palmar',
  'Sipí',
  'Tadó',
  'Unión Panamericana',
  'Unguía'
]) AS c WHERE name = 'CHOCÓ';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Ayapel',
  'Buenavista',
  'Canalete',
  'Cereté',
  'Chimá',
  'Chinú',
  'Ciénaga de Oro',
  'Cotorra',
  'La Apartada',
  'Lorica',
  'Los Córdobas',
  'Momil',
  'Montelíbano',
  'Montería',
  'Moñitos',
  'Planeta Rica',
  'Pueblo Nuevo',
  'Puerto Escondido',
  'Puerto Libertador',
  'Purísima',
  'Sahagún',
  'San Andrés de Sotavento',
  'San Antero',
  'San Bernardo del Viento',
  'San Carlos',
  'San José de Uré',
  'San Pelayo',
  'Tierralta',
  'Tuchín',
  'Valencia'
]) AS c WHERE name = 'CÓRDOBA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Agua de Dios',
  'Albán',
  'Anapoima',
  'Anolaima',
  'Apulo',
  'Arbeláez',
  'Beltrán',
  'Bituima',
  'Bojacá',
  'Cabrera',
  'Cachipay',
  'Cajicá',
  'Caparrapí',
  'Cáqueza',
  'Carmen de Carupa',
  'Chaguaní',
  'Chía',
  'Chipaque',
  'Choachí',
  'Chocontá',
  'Cogua',
  'Cota',
  'Cucunubá',
  'El Colegio',
  'El Peñón',
  'El Rosal',
  'Facatativá',
  'Fómeque',
  'Fosca',
  'Funza',
  'Fúquene',
  'Fusagasugá',
  'Gachalá',
  'Gachancipá',
  'Gachetá',
  'Gama',
  'Girardot',
  'Granada',
  'Guachetá',
  'Guaduas',
  'Guasca',
  'Guataquí',
  'Guatavita',
  'Guayabal de Síquima',
  'Guayabetal',
  'Gutiérrez',
  'Jerusalén',
  'Junín',
  'La Calera',
  'La Mesa',
  'La Palma',
  'La Peña',
  'La Vega',
  'Lenguazaque',
  'Machetá',
  'Madrid',
  'Manta',
  'Medina',
  'Mosquera',
  'Nariño',
  'Nemocón',
  'Nilo',
  'Nimaima',
  'Nocaima',
  'Pacho',
  'Paime',
  'Pandi',
  'Paratebueno',
  'Pasca',
  'Puerto Salgar',
  'Pulí',
  'Quebradanegra',
  'Quetame',
  'Quipile',
  'Ricaurte',
  'San Antonio del Tequendama',
  'San Bernardo',
  'San Cayetano',
  'San Francisco',
  'San Juan de Rioseco',
  'Sasaima',
  'Sesquilé',
  'Sibaté',
  'Silvania',
  'Simijaca',
  'Soacha',
  'Sopó',
  'Subachoque',
  'Suesca',
  'Supatá',
  'Susa',
  'Sutatausa',
  'Tabio',
  'Tausa',
  'Tena',
  'Tenjo',
  'Tibacuy',
  'Tibirita',
  'Tocaima',
  'Tocancipá',
  'Topaipí',
  'Ubalá',
  'Ubaque',
  'Ubaté',
  'Une',
  'Útica',
  'Venecia',
  'Vergara',
  'Vianí',
  'Villagómez',
  'Villapinzón',
  'Villeta',
  'Viotá',
  'Yacopí',
  'Zipacón',
  'Zipaquirá'
]) AS c WHERE name = 'CUNDINAMARCA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Inírida'
]) AS c WHERE name = 'GUAINÍA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Calamar',
  'El Retorno',
  'Miraflores',
  'San José del Guaviare'
]) AS c WHERE name = 'GUAVIARE';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Acevedo',
  'Agrado',
  'Aipe',
  'Algeciras',
  'Altamira',
  'Baraya',
  'Campoalegre',
  'Colombia',
  'El Pital',
  'Elías',
  'Garzón',
  'Gigante',
  'Guadalupe',
  'Hobo',
  'Íquira',
  'Isnos',
  'La Argentina',
  'La Plata',
  'Nátaga',
  'Neiva',
  'Oporapa',
  'Paicol',
  'Palermo',
  'Palestina',
  'Pitalito',
  'Rivera',
  'Saladoblanco',
  'San Agustín',
  'Santa María',
  'Suaza',
  'Tarqui',
  'Tello',
  'Teruel',
  'Tesalia',
  'Timaná',
  'Villavieja',
  'Yaguará'
]) AS c WHERE name = 'HUILA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Albania',
  'Barrancas',
  'Dibulla',
  'Distracción',
  'El Molino',
  'Fonseca',
  'Hatonuevo',
  'La Jagua del Pilar',
  'Maicao',
  'Manaure',
  'Riohacha',
  'San Juan del Cesar',
  'Uribia',
  'Urumita',
  'Villanueva'
]) AS c WHERE name = 'LA GUAJIRA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Algarrobo',
  'Aracataca',
  'Ariguaní',
  'Cerro de San Antonio',
  'Chibolo',
  'Ciénaga',
  'Concordia',
  'El Banco',
  'El Piñón',
  'El Retén',
  'Fundación',
  'Guamal',
  'Nueva Granada',
  'Pedraza',
  'Pijiño del Carmen',
  'Pivijay',
  'Plato',
  'Pueblo Viejo',
  'Remolino',
  'Sabanas de San Ángel',
  'Salamina',
  'San Sebastián de Buenavista',
  'San Zenón',
  'Santa Ana',
  'Santa Bárbara de Pinto',
  'Santa Marta',
  'Sitionuevo',
  'Tenerife',
  'Zapayán',
  'Zona Bananera'
]) AS c WHERE name = 'MAGDALENA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Acacías',
  'Barranca de Upía',
  'Cabuyaro',
  'Castilla la Nueva',
  'Cubarral',
  'Cumaral',
  'El Calvario',
  'El Castillo',
  'El Dorado',
  'Fuente de Oro',
  'Granada',
  'Guamal',
  'La Macarena',
  'La Uribe',
  'Lejanías',
  'Mapiripán',
  'Mesetas',
  'Puerto Concordia',
  'Puerto Gaitán',
  'Puerto Lleras',
  'Puerto López',
  'Puerto Rico',
  'Restrepo',
  'San Carlos de Guaroa',
  'San Juan de Arama',
  'San Juanito',
  'San Martín',
  'Villavicencio',
  'Vista Hermosa'
]) AS c WHERE name = 'META';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Aldana',
  'Ancuyá',
  'Arboleda',
  'Barbacoas',
  'Belén',
  'Buesaco',
  'Chachagüí',
  'Colón',
  'Consacá',
  'Contadero',
  'Córdoba',
  'Cuaspud',
  'Cumbal',
  'Cumbitara',
  'El Charco',
  'El Peñol',
  'El Rosario',
  'El Tablón',
  'El Tambo',
  'Francisco Pizarro',
  'Funes',
  'Guachucal',
  'Guaitarilla',
  'Gualmatán',
  'Iles',
  'Imués',
  'Ipiales',
  'La Cruz',
  'La Florida',
  'La Llanada',
  'La Tola',
  'La Unión',
  'Leiva',
  'Linares',
  'Los Andes',
  'Magüí Payán',
  'Mallama',
  'Mosquera',
  'Nariño',
  'Olaya Herrera',
  'Ospina',
  'Pasto',
  'Policarpa',
  'Potosí',
  'Providencia',
  'Puerres',
  'Pupiales',
  'Ricaurte',
  'Roberto Payán',
  'Samaniego',
  'San Bernardo',
  'San José de Albán',
  'San Lorenzo',
  'San Pablo',
  'San Pedro de Cartago',
  'Sandoná',
  'Santa Bárbara',
  'Santacruz',
  'Sapuyes',
  'Taminango',
  'Tangua',
  'Tumaco',
  'Túquerres',
  'Yacuanquer'
]) AS c WHERE name = 'NARIÑO';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Ábrego',
  'Arboledas',
  'Bochalema',
  'Bucarasica',
  'Cáchira',
  'Cácota',
  'Chinácota',
  'Chitagá',
  'Convención',
  'Cúcuta',
  'Cucutilla',
  'Duranía',
  'El Carmen',
  'El Tarra',
  'El Zulia',
  'Gramalote',
  'Hacarí',
  'Herrán',
  'La Esperanza',
  'La Playa de Belén',
  'Labateca',
  'Los Patios',
  'Lourdes',
  'Mutiscua',
  'Ocaña',
  'Pamplona',
  'Pamplonita',
  'Puerto Santander',
  'Ragonvalia',
  'Salazar de Las Palmas',
  'San Calixto',
  'San Cayetano',
  'Santiago',
  'Santo Domingo de Silos',
  'Sardinata',
  'Teorama',
  'Tibú',
  'Toledo',
  'Villa Caro',
  'Villa del Rosario'
]) AS c WHERE name = 'NORTE DE SANTANDER';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Colón',
  'Mocoa',
  'Orito',
  'Puerto Asís',
  'Puerto Caicedo',
  'Puerto Guzmán',
  'Puerto Leguízamo',
  'San Francisco',
  'San Miguel',
  'Santiago',
  'Sibundoy',
  'Valle del Guamuez',
  'Villagarzón'
]) AS c WHERE name = 'PUTUMAYO';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Armenia',
  'Buenavista',
  'Calarcá',
  'Circasia',
  'Córdoba',
  'Filandia',
  'Génova',
  'La Tebaida',
  'Montenegro',
  'Pijao',
  'Quimbaya',
  'Salento'
]) AS c WHERE name = 'QUINDÍO';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Apía',
  'Balboa',
  'Belén de Umbría',
  'Dosquebradas',
  'Guática',
  'La Celia',
  'La Virginia',
  'Marsella',
  'Mistrató',
  'Pereira',
  'Pueblo Rico',
  'Quinchía',
  'Santa Rosa de Cabal',
  'Santuario'
]) AS c WHERE name = 'RISARALDA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Providencia y Santa Catalina Islas',
  'San Andrés'
]) AS c WHERE name = 'SAN ANDRÉS Y PROVIDENCIA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Aguada',
  'Albania',
  'Aratoca',
  'Barbosa',
  'Barichara',
  'Barrancabermeja',
  'Betulia',
  'Bolívar',
  'Bucaramanga',
  'Cabrera',
  'California',
  'Capitanejo',
  'Carcasí',
  'Cepitá',
  'Cerrito',
  'Charalá',
  'Charta',
  'Chima',
  'Chipatá',
  'Cimitarra',
  'Concepción',
  'Confines',
  'Contratación',
  'Coromoro',
  'Curití',
  'El Carmen de Chucurí',
  'El Guacamayo',
  'El Peñón',
  'El Playón',
  'El Socorro',
  'Encino',
  'Enciso',
  'Florián',
  'Floridablanca',
  'Galán',
  'Gámbita',
  'Girón',
  'Guaca',
  'Guadalupe',
  'Guapotá',
  'Guavatá',
  'Güepsa',
  'Hato',
  'Jesús María',
  'Jordán',
  'La Belleza',
  'La Paz',
  'Landázuri',
  'Lebrija',
  'Los Santos',
  'Macaravita',
  'Málaga',
  'Matanza',
  'Mogotes',
  'Molagavita',
  'Ocamonte',
  'Oiba',
  'Onzaga',
  'Palmar',
  'Palmas del Socorro',
  'Páramo',
  'Piedecuesta',
  'Pinchote',
  'Puente Nacional',
  'Puerto Parra',
  'Puerto Wilches',
  'Rionegro',
  'Sabana de Torres',
  'San Andrés',
  'San Benito',
  'San Gil',
  'San Joaquín',
  'San José de Miranda',
  'San Miguel',
  'San Vicente de Chucurí',
  'Santa Bárbara',
  'Santa Helena del Opón',
  'Simacota',
  'Suaita',
  'Sucre',
  'Suratá',
  'Tona',
  'Valle de San José',
  'Vélez',
  'Vetas',
  'Villanueva',
  'Zapatoca'
]) AS c WHERE name = 'SANTANDER';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Buenavista',
  'Caimito',
  'Chalán',
  'Colosó',
  'Corozal',
  'Coveñas',
  'El Roble',
  'Galeras',
  'Guaranda',
  'La Unión',
  'Los Palmitos',
  'Majagual',
  'Morroa',
  'Ovejas',
  'Sampués',
  'San Antonio de Palmito',
  'San Benito Abad',
  'San Juan de Betulia',
  'San Marcos',
  'San Onofre',
  'San Pedro',
  'Sincé',
  'Sincelejo',
  'Sucre',
  'Tolú',
  'Tolú Viejo'
]) AS c WHERE name = 'SUCRE';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Alpujarra',
  'Alvarado',
  'Ambalema',
  'Anzoátegui',
  'Armero',
  'Ataco',
  'Cajamarca',
  'Carmen de Apicalá',
  'Casabianca',
  'Chaparral',
  'Coello',
  'Coyaima',
  'Cunday',
  'Dolores',
  'El Espinal',
  'Falán',
  'Flandes',
  'Fresno',
  'Guamo',
  'Herveo',
  'Honda',
  'Ibagué',
  'Icononzo',
  'Lérida',
  'Líbano',
  'Mariquita',
  'Melgar',
  'Murillo',
  'Natagaima',
  'Ortega',
  'Palocabildo',
  'Piedras',
  'Planadas',
  'Prado',
  'Purificación',
  'Rioblanco',
  'Roncesvalles',
  'Rovira',
  'Saldaña',
  'San Antonio',
  'San Luis',
  'Santa Isabel',
  'Suárez',
  'Valle de San Juan',
  'Venadillo',
  'Villahermosa',
  'Villarrica'
]) AS c WHERE name = 'TOLIMA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Alcalá',
  'Andalucía',
  'Ansermanuevo',
  'Argelia',
  'Bolívar',
  'Buenaventura',
  'Buga',
  'Bugalagrande',
  'Caicedonia',
  'Cali',
  'Calima',
  'Candelaria',
  'Cartago',
  'Dagua',
  'El Águila',
  'El Cairo',
  'El Cerrito',
  'El Dovio',
  'Florida',
  'Ginebra',
  'Guacarí',
  'Jamundí',
  'La Cumbre',
  'La Unión',
  'La Victoria',
  'Obando',
  'Palmira',
  'Pradera',
  'Restrepo',
  'Riofrío',
  'Roldanillo',
  'San Pedro',
  'Sevilla',
  'Toro',
  'Trujillo',
  'Tuluá',
  'Ulloa',
  'Versalles',
  'Vijes',
  'Yotoco',
  'Yumbo',
  'Zarzal'
]) AS c WHERE name = 'VALLE DEL CAUCA';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Carurú',
  'Mitú',
  'Taraira'
]) AS c WHERE name = 'VAUPÉS';

INSERT INTO geo_cities (department_id, name)
SELECT id, c FROM geo_departments, unnest(ARRAY[
  'Cumaribo',
  'La Primavera',
  'Puerto Carreño',
  'Santa Rosalía'
]) AS c WHERE name = 'VICHADA';

